# Generated by Django 4.0.3 on 2022-04-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskshare'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskshare',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_task_share'),
        ),
    ]
