# Generated by Django 4.0.3 on 2022-04-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskshare',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
