# Generated by Django 4.0.3 on 2022-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_tasknotification_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskshare',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
