# Generated by Django 4.0.3 on 2022-04-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_tasknotification_task_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknotification',
            name='comment',
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
